apiVersion: v1
kind: ConfigMap
metadata: 
  name: configmap-demo
  labels: 
    purpose: configmap-demo 
    project: roboshop
data: 
  COURSE:   "DevOps with AWS"
  DURATION: "120 HOURS"
  TRAINER:  "SHIVAKUMAR"