apiVersion: v1
kind: Pod
metadata:
  name: env-secret
  labels:
    project: roboshop
    purpose: demo-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:            
        name: pod-secret    # this is from 10-secret.yaml name
